---
name: Docker Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
            
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          ### REQUIRED
          ### ENABLE ONE OR BOTH REGISTRIES
          ### tell docker where to push.
          ### NOTE if Docker Hub is set to true, you must set secrets above and also add account/repo/tags below
          # dockerhub-enable: true

          ### REQUIRED 
          ### A list of the account/repo names for docker build. List should match what's enabled above
          ### defaults to:
          tags: tclayton0594/examplevotingapp_vote

          ### REQUIRED set rules for tagging images, based on special action syntax:
          ### https://github.com/docker/metadata-action#tags-input
          ### defaults to:
          # tag-rules: |
          #   type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
          #   type=ref,event=pr
          #   type=ref,event=branch
          #   type=semver,pattern={{version}}
          #   type=raw,value=gha-${{ github.run_id }}
          
          ### path to where docker should copy files into image
          ### defaults to root of repository (.)
          context: "{{defaultContext}}:vote"

          push: ${{ github.event_name != 'pull_request' }}

          # Use BuildKit building engine to cache layers of images while building to speed up future builds
          cache-from: type=gha
          cache-to: type=gha,mode=max

          
          ### Dockerfile alternate name. Default is Dockerfile (relative to context path)
          # file: Containerfile

          ### build stage to target, defaults to empty, which builds to last stage in Dockerfile
          # target:
          
          ### platforms to build for, defaults to linux/amd64
          ### other options: linux/amd64,linux/arm64,linux/arm/v7
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          
          ### Create a PR comment with image tags and labels
          ### defaults to false
          # comment-enable: false

          