---
name: Docker Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
            
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: tclayton0594/examplevotingapp_vote
          
          ### path to where docker should copy files into image
          ### defaults to root of repository (.)
          context: "{{defaultContext}}:vote"

          # Use BuildKit building engine to cache layers of images while building to speed up future builds
          cache-from: type=gha
          cache-to: type=gha,mode=max

          